export const FETCH_ALL_SOAL_DISC = "FETCH_ALL_SOAL_DISC";
export const FETCH_ALL_SOAL_MBTI1 = "FETCH_ALL_SOAL_MBTI1";
export const FETCH_ALL_SOAL_MBTI2 = "FETCH_ALL_SOAL_MBTI2";
export const FETCH_ALL_SOAL_MBTI3 = "FETCH_ALL_SOAL_MBTI3";
